server:
  port: 8087
  servlet:
    context-path: /crm
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
spring:
  application:
    name: limmaGatewayCRM
