server:
  port: 8082
  servlet:
    context-path: /product
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
spring:
  application:
    name: limmaProduct
  datasource:
    url: jdbc:postgresql://localhost:5432/sapa?createDatabaseIfNotExist=true
    username: sapa
    password: sapa_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springfox:
  documentation:
    swagger:
      v2:
        path:
